/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Controlador;
import javax.swing.JOptionPane;


public class VistaBusquedaProductos extends javax.swing.JFrame {

    
    private Controlador miControlador;
    
    
    public VistaBusquedaProductos() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BuscarPorCombo = new javax.swing.JComboBox<>();
        Buscarpor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        NombreEntry = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        EditarProducto = new javax.swing.JButton();
        EliminarProducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Producto");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        BuscarPorCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Nombre", "Sección" }));
        BuscarPorCombo.setToolTipText("");
        BuscarPorCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPorComboActionPerformed(evt);
            }
        });

        Buscarpor.setText("Buscar por:");

        jLabel1.setText("Nombre");

        NombreEntry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NombreEntryKeyReleased(evt);
            }
        });

        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Sección", "Nombre", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaProductos);

        EditarProducto.setText("Editar");
        EditarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarProductoActionPerformed(evt);
            }
        });

        EliminarProducto.setText("Eliminar");
        EliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(Buscarpor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BuscarPorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NombreEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(EditarProducto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EliminarProducto)))
                        .addGap(0, 223, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buscarpor)
                    .addComponent(BuscarPorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditarProducto)
                    .addComponent(EliminarProducto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarPorComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPorComboActionPerformed
        System.out.println("Realizando nueva consulta de productos a BBDD");
        if(!NombreEntry.getText().isEmpty() || BuscarPorCombo.getSelectedIndex()==0){
            TablaProductos.setModel(miControlador.buscarProducto(NombreEntry.getText(), BuscarPorCombo.getSelectedIndex()));
        }
        else{
            TablaProductos.setModel(miControlador.buscarProducto("", 0));
        }
    }//GEN-LAST:event_BuscarPorComboActionPerformed

    private void EditarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarProductoActionPerformed
        //FIJARSE SI SE SELECCIONÓ UN PRODUCTO Y LUEGO MOSTRAR EL FORMULARIO.
        int filaSeleccionada = TablaProductos.getSelectedRow();
        if(filaSeleccionada >= 0){
            
            String Codigo = (String) TablaProductos.getModel().getValueAt(filaSeleccionada, 0); // Guarda en "Codigo" un string que captura de la fila seleccionada y la columna indicada de la tabla cargada con el MODEL
            String Seccion = (String) TablaProductos.getModel().getValueAt(filaSeleccionada, 1);
            String Nombre = (String) TablaProductos.getModel().getValueAt(filaSeleccionada, 2);
            String Precio = (String) TablaProductos.getModel().getValueAt(filaSeleccionada, 3);
                       
            System.out.println("Editando el producto codigo: "+Codigo);
            
            miControlador.abrirPantallaEditarProducto(Codigo, Seccion, Nombre, Precio);
        }else{
            JOptionPane.showMessageDialog(null, "Por favor seleccione un producto");
        }
         
    }//GEN-LAST:event_EditarProductoActionPerformed

    private void EliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarProductoActionPerformed
        // TODO add your handling code here:
        //CAPTURAR EL PRODUCTO SELECCIONADO DEL LISTADO, COMPROBAR QUE NO ES NULO y SEGUIR
        int filaSeleccionada = TablaProductos.getSelectedRow();
        if(filaSeleccionada >= 0){
            
            String Codigo = (String) TablaProductos.getModel().getValueAt(filaSeleccionada, 0);
            System.out.println("Eliminando el producto codigo: "+Codigo);
            int opcion = JOptionPane.showConfirmDialog(null, "Realmente desea eliminar el producto?" , "Eliminar producto", JOptionPane.YES_NO_OPTION);
            System.out.println(opcion);
            if(opcion==0)
            {
                miControlador.eliminarProducto(Codigo);
            }
           
        }else{
            JOptionPane.showMessageDialog(null, "Por favor seleccione un producto");
        }
    }//GEN-LAST:event_EliminarProductoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        TablaProductos.setModel(miControlador.buscarProducto("", 0));
        BuscarPorCombo.setSelectedIndex(0);
        NombreEntry.setText("");
    }//GEN-LAST:event_formWindowActivated

    private void NombreEntryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreEntryKeyReleased
        System.out.println("Realizando nueva consulta de productos a BBDD");
        if(!NombreEntry.getText().isEmpty() || BuscarPorCombo.getSelectedIndex()==0){
            TablaProductos.setModel(miControlador.buscarProducto(NombreEntry.getText(), BuscarPorCombo.getSelectedIndex()));
        }
        else{
            TablaProductos.setModel(miControlador.buscarProducto("", 0));
        }
    }//GEN-LAST:event_NombreEntryKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaBusquedaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaBusquedaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaBusquedaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaBusquedaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaBusquedaProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BuscarPorCombo;
    private javax.swing.JLabel Buscarpor;
    private javax.swing.JButton EditarProducto;
    private javax.swing.JButton EliminarProducto;
    private javax.swing.JTextField NombreEntry;
    private javax.swing.JTable TablaProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
 

    public void setControlador(Controlador miControlador) {
      this.miControlador = miControlador; 
    }
    


}
