package vista;

import controlador.Controlador;
import javax.swing.JOptionPane;


public class VistaBusquedaClientes extends javax.swing.JFrame {

    
    private Controlador miControlador;
    
    
    public VistaBusquedaClientes() {
        initComponents();
    }

     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BuscarPorCombo = new javax.swing.JComboBox<>();
        Buscarpor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        NombreEntry = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaClientes = new javax.swing.JTable();
        EditarCliente = new javax.swing.JButton();
        EliminarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Cliente");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        BuscarPorCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Empresa", "Responsable" }));
        BuscarPorCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPorComboActionPerformed(evt);
            }
        });

        Buscarpor.setText("Buscar por:");

        jLabel1.setText("Nombre");

        NombreEntry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NombreEntryKeyReleased(evt);
            }
        });

        TablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Empresa", "Dirección", "Provincia", "Teléfono", "Responsable"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaClientes);

        EditarCliente.setText("Editar");
        EditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarClienteActionPerformed(evt);
            }
        });

        EliminarCliente.setText("Eliminar");
        EliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(EditarCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EliminarCliente))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(Buscarpor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BuscarPorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NombreEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buscarpor)
                    .addComponent(BuscarPorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditarCliente)
                    .addComponent(EliminarCliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarClienteActionPerformed
        //FIJARSE SI SE SELECCIONÓ UN CLIENTE Y LUEGO MOSTRAR EL FORMULARIO.
        int filaSeleccionada = TablaClientes.getSelectedRow();
        if(filaSeleccionada >= 0){
            
            String Codigo = (String) TablaClientes.getModel().getValueAt(filaSeleccionada, 0);
            String Empresa = (String) TablaClientes.getModel().getValueAt(filaSeleccionada, 1);
            String Direccion = (String) TablaClientes.getModel().getValueAt(filaSeleccionada, 2);
            String Provincia = (String) TablaClientes.getModel().getValueAt(filaSeleccionada, 3);
            String Telefono = (String) TablaClientes.getModel().getValueAt(filaSeleccionada, 4);
            String Responsable = (String) TablaClientes.getModel().getValueAt(filaSeleccionada, 5);
            
            System.out.println("Editando el cliente codigo: "+Codigo);
            
            miControlador.abrirPantallaEditarCliente(Codigo, Empresa, Direccion, Provincia, Telefono, Responsable);
        }else{
            JOptionPane.showMessageDialog(null, "Por favor seleccione un cliente");
        }
        
    }//GEN-LAST:event_EditarClienteActionPerformed

    private void EliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarClienteActionPerformed
        int filaSeleccionada = TablaClientes.getSelectedRow();
        if(filaSeleccionada >= 0){
            
            String Codigo = (String) TablaClientes.getModel().getValueAt(filaSeleccionada, 0);
            System.out.println("Eliminando el cliente codigo: "+Codigo);
            int opcion = JOptionPane.showConfirmDialog(null, "Realmente desea eliminar el cliente?" , "Eliminar cliente", JOptionPane.YES_NO_OPTION);
            System.out.println(opcion);
            if(opcion==0)
            {
                miControlador.eliminarCliente(Codigo);
            }
           
        }else{
            JOptionPane.showMessageDialog(null, "Por favor seleccione un cliente");
        }
        
    }//GEN-LAST:event_EliminarClienteActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        TablaClientes.setModel(miControlador.buscarCliente("", 0));
        BuscarPorCombo.setSelectedIndex(0);
        NombreEntry.setText("");
        
    }//GEN-LAST:event_formWindowActivated

    private void NombreEntryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreEntryKeyReleased
        //Evento que se dispara cuando se inserta una letra en el cuadro de texto
        System.out.println("Realizando nueva consulta de clientes a BBDD");
        if(!NombreEntry.getText().isEmpty() || BuscarPorCombo.getSelectedIndex()==0){
            TablaClientes.setModel(miControlador.buscarCliente(NombreEntry.getText(), BuscarPorCombo.getSelectedIndex()));
        }
        else{
            TablaClientes.setModel(miControlador.buscarCliente("", 0));
        }
    }//GEN-LAST:event_NombreEntryKeyReleased

    private void BuscarPorComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPorComboActionPerformed
        System.out.println("Realizando nueva consulta de clientes a BBDD");
        if(!NombreEntry.getText().isEmpty() || BuscarPorCombo.getSelectedIndex()==0){
            TablaClientes.setModel(miControlador.buscarCliente(NombreEntry.getText(), BuscarPorCombo.getSelectedIndex()));
        }
        else{
            TablaClientes.setModel(miControlador.buscarCliente("", 0));
        }
    }//GEN-LAST:event_BuscarPorComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaBusquedaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaBusquedaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaBusquedaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaBusquedaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaBusquedaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BuscarPorCombo;
    private javax.swing.JLabel Buscarpor;
    private javax.swing.JButton EditarCliente;
    private javax.swing.JButton EliminarCliente;
    private javax.swing.JTextField NombreEntry;
    private javax.swing.JTable TablaClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
 

    public void setControlador(Controlador miControlador) {
      this.miControlador = miControlador; 
    }
    


}
