/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Controlador;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



public class VistaEditarPedido extends javax.swing.JFrame {

    
    private Controlador miControlador;
    private String codigo;
    private String codigoCliente;
    
    
    public VistaEditarPedido() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        agregarProducto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaProductosPedidos = new javax.swing.JTable();
        quitarProducto = new javax.swing.JButton();
        ActualizarPedido = new javax.swing.JButton();
        SeleccionarCliente = new javax.swing.JButton();
        ClienteEntry = new javax.swing.JTextField();
        Buscarpor = new javax.swing.JLabel();
        BuscarPorCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        NombreEntry = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Pedido");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Cliente");

        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Sección", "Nombre", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaProductos);

        agregarProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        agregarProducto.setText("+");
        agregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProductoActionPerformed(evt);
            }
        });

        TablaProductosPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Sección", "Nombre", "Precio", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TablaProductosPedidos);

        quitarProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        quitarProducto.setText("-");
        quitarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarProductoActionPerformed(evt);
            }
        });

        ActualizarPedido.setText("Actualizar");
        ActualizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarPedidoActionPerformed(evt);
            }
        });

        SeleccionarCliente.setText("Seleccionar");
        SeleccionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarClienteActionPerformed(evt);
            }
        });

        ClienteEntry.setText("miCliente");
        ClienteEntry.setFocusable(false);
        ClienteEntry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ClienteEntryKeyTyped(evt);
            }
        });

        Buscarpor.setText("Buscar por:");

        BuscarPorCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Nombre", "Sección" }));
        BuscarPorCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPorComboActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        NombreEntry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NombreEntryKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreEntryKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ActualizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(agregarProducto)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ClienteEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SeleccionarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quitarProducto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Buscarpor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BuscarPorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NombreEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ClienteEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeleccionarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(agregarProducto)
                        .addGap(62, 62, 62))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Buscarpor)
                            .addComponent(BuscarPorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(quitarProducto)
                        .addGap(68, 68, 68)))
                .addComponent(ActualizarPedido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void agregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProductoActionPerformed
          int filaSeleccionada = TablaProductos.getSelectedRow();
        if(filaSeleccionada >= 0){
            
            String Codigo = (String) TablaProductos.getModel().getValueAt(filaSeleccionada, 0); // Guarda en "Codigo" un string que captura de la fila seleccionada y la columna indicada de la tabla cargada con el MODEL
            String Seccion = (String) TablaProductos.getModel().getValueAt(filaSeleccionada, 1);
            String Nombre = (String) TablaProductos.getModel().getValueAt(filaSeleccionada, 2);
            String Precio = (String) TablaProductos.getModel().getValueAt(filaSeleccionada, 3);
                       
            System.out.println("Agregando el producto codigo: "+Codigo);
            
            DefaultTableModel Modelo = (DefaultTableModel)TablaProductosPedidos.getModel(); // Se castea un TableModel a DefaultTableModel ya que necesito usar el método addRow que TableModel no tiene
                                                                                            // DefaultTableModel es una implementación de la interfaz TableModel
            Modelo.addRow(new Object[]{Codigo, Seccion, Nombre, Precio, "1"});
            
        }else{
            JOptionPane.showMessageDialog(null, "Por favor seleccione un producto");
        }
    }//GEN-LAST:event_agregarProductoActionPerformed

    private void quitarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarProductoActionPerformed
        int filaSeleccionada = TablaProductosPedidos.getSelectedRow();
        if(filaSeleccionada >= 0){
            
            String Codigo = (String) TablaProductosPedidos.getModel().getValueAt(filaSeleccionada, 0); // Guarda en "Codigo" un string que captura de la fila seleccionada y la columna indicada de la tabla cargada con el MODEL
            System.out.println("Quitando el producto codigo: "+Codigo);
            
            DefaultTableModel Modelo = (DefaultTableModel)TablaProductosPedidos.getModel(); // Se castea un TableModel a DefaultTableModel ya que necesito usar el método addRow que TableModel no tiene
                                                                                            // DefaultTableModel es una implementación de la interfaz TableModel
            Modelo.removeRow(filaSeleccionada);
            
        }else{
            JOptionPane.showMessageDialog(null, "Por favor seleccione un producto");
        } 
    }//GEN-LAST:event_quitarProductoActionPerformed

    private void ActualizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarPedidoActionPerformed
        
        miControlador.ActualizarClienteEnPedido(codigo, codigoCliente);
        miControlador.ActualizarProductosPedido(codigo, TablaProductosPedidos.getModel());
        JOptionPane.showMessageDialog(null, "Pedido actualizado"); 
        dispose();
        
    }//GEN-LAST:event_ActualizarPedidoActionPerformed

    private void SeleccionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarClienteActionPerformed
        miControlador.abrirPantallaSeleccionCliente();
    }//GEN-LAST:event_SeleccionarClienteActionPerformed

    private void ClienteEntryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ClienteEntryKeyTyped
        if(ClienteEntry.getText().length() >= 30)
        {
            evt.consume(); //evt.consume() eso quiere decir que el evento se consumirá e impide en este caso, el ingreso de mas caracteres.
            System.out.println("Ha llegado al maximo de caracteres en el campo");
        }
    }//GEN-LAST:event_ClienteEntryKeyTyped

    private void BuscarPorComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPorComboActionPerformed
        System.out.println("Realizando nueva consulta de productos a BBDD");
        if(!NombreEntry.getText().isEmpty() || BuscarPorCombo.getSelectedIndex()==0){
            TablaProductos.setModel(miControlador.buscarProducto(NombreEntry.getText(), BuscarPorCombo.getSelectedIndex()));
        }
        else{
            TablaProductos.setModel(miControlador.buscarProducto("", 0));
        }
    }//GEN-LAST:event_BuscarPorComboActionPerformed

    private void NombreEntryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreEntryKeyTyped
        if(NombreEntry.getText().length() >= 30)
        {
            evt.consume(); //evt.consume() eso quiere decir que el evento se consumirá e impide en este caso, el ingreso de mas caracteres.
            System.out.println("Ha llegado al maximo de caracteres en el campo");
        }
    }//GEN-LAST:event_NombreEntryKeyTyped

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        TablaProductos.setModel(miControlador.buscarProducto("", 0));
        BuscarPorCombo.setSelectedIndex(0);
        NombreEntry.setText("");
    }//GEN-LAST:event_formWindowActivated

    private void NombreEntryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreEntryKeyReleased
        System.out.println("Realizando nueva consulta de productos a BBDD");
        if(!NombreEntry.getText().isEmpty() || BuscarPorCombo.getSelectedIndex()==0){
            TablaProductos.setModel(miControlador.buscarProducto(NombreEntry.getText(), BuscarPorCombo.getSelectedIndex()));
        }
        else{
            TablaProductos.setModel(miControlador.buscarProducto("", 0));
        }
    }//GEN-LAST:event_NombreEntryKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        System.out.println("EJECUTADO");
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaEditarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaEditarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaEditarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaEditarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaEditarPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarPedido;
    private javax.swing.JComboBox<String> BuscarPorCombo;
    private javax.swing.JLabel Buscarpor;
    private javax.swing.JTextField ClienteEntry;
    private javax.swing.JTextField NombreEntry;
    private javax.swing.JButton SeleccionarCliente;
    private javax.swing.JTable TablaProductos;
    private javax.swing.JTable TablaProductosPedidos;
    private javax.swing.JButton agregarProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton quitarProducto;
    // End of variables declaration//GEN-END:variables
 

    public void setControlador(Controlador miControlador) {
      this.miControlador = miControlador; 
    }

    public void cargaFormulario(String Codigo, String CodigoCliente, String Nombre) {
        this.codigo=Codigo;
        
        TablaProductosPedidos.setModel(miControlador.buscarProductosPedidos(Codigo));
        
        this.codigoCliente=CodigoCliente;
        ClienteEntry.setText(Nombre);
    }

    public void setClienteEntry(String ClienteSeleccionado, String Codigo) {
        this.ClienteEntry.setText(ClienteSeleccionado);
        this.codigoCliente=Codigo;
    }

}
